### ISSUE TITLE
`change-log -a` must not expect tags.

### ISSUE THREAD

**Issue by hemanth** [tj/git-extras#338] opened 2015-03-20 12:29 UTC
```
± |master ✓| → git-changelog -l -a

ERROR:  Specified start-tag does not exist!

```
```
  -a, --all                 Retrieve all commits (ignores --start-tag, --final-tag)
  -l, --list                Display commits as a list, with no titles
```

**Comment by markeissler** [comment] 2015-04-16 16:22
Sorry, I didn't see this. Will take a look.

**Comment by markeissler** [comment] 2015-04-16 20:42
This is a duplicate of #337.

**Closed** 2015-04-27 12:43 UTC
