### ISSUE TITLE
 <bug> with 'git changelog -x' in version 3.0.0

### ISSUE THREAD

**Issue by Shea690901** [tj/git-extras#484] opened 2015-11-30 19:03 UTC
When suppling '-x' as option one doesn't get the output on stdout but an error message

    cat: can't open '': No such file or directory

git changelog called with the same options _except_ '-x' works as expected and opens the file in the configured editor…

**Comment by spacewander** [comment] 2015-12-01 02:13
What options did you use? 
Also, could you paste the output of `cat $(which git-changelog)`?

**Comment by Shea690901** [comment] 2015-12-01 07:15
it was regardless of other options…
But i think we might close this issue, as i've found that in the current development version the bug is no longer present…

**Comment by spacewander** [comment] 2015-12-01 08:56
Err, the result why I asked the options is that I could not reproduce the bug with `git changelog -x [another_option]` in version 3.0. So I suspected if a specific combination of options causes the bug.

Anyway, if you think your problem is solved, you can close the issue as you like.

**Closed** 2015-12-01 12:30 UTC
