### ISSUE TITLE
git fork fails with "Not found" message

### ISSUE THREAD

**Issue by logological** [tj/git-extras#542] opened 2016-06-26 16:17 UTC
The `git fork` command doesn't work for me, no matter whether I specify HTTPS or SSH as the access method.  It returns a "Not found" message when trying to access the repository I want to fork; this causes the subsequent creation and checkout of the fork to fail.

```
$ git fork git@github.com:edobashira/speech-language-processing.git
Enter your github username
logological
Enter host password for user 'logological':
{
  "message": "Not Found",
  "documentation_url": "https://developer.github.com/v3"
}
Cloning into 'speech-language-processing.git'...
remote: Repository not found.
fatal: repository 'https://github.com/logological/speech-language-processing.git/' not found
/usr/local/bin/git-fork: line 41: cd: speech-language-processing.git: No such file or directory
fatal: Not a git repository (or any parent up to mount point /home)
Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).
fatal: Not a git repository (or any parent up to mount point /home)
Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).
```

**Comment by spacewander** [comment] 2016-06-27 06:08
@logological 
Could you check out this branch https://github.com/tj/git-extras/pull/543 and confirm if the problem is fixed?

**Comment by logological** [comment] 2016-06-27 07:28
Still failing for me.  Though on rereading the documentation, it seems the reason I got the error in the first place is that I didn't invoke the command correctly.  The `git fork` command expects as its argument the URL of the project's GitHub page, whereas I had been passing the URL used to clone the repository.

I expect this is not an unusual mistake – I was expecting `git fork` to act like `git clone`.  Perhaps the command could be rewritten so that it also works with the usual clone URLs?  Possibly all you need to do is remove the trailing `.git` extension.  (As far as I know, GitHub won't let you create a repository with this extension, so there should be no ambiguity.)

**Comment by spacewander** [comment] 2016-06-27 11:51
@logological @hemanth 
Sorry, it's my mistake...
I fix it in a new pr: https://github.com/tj/git-extras/pull/545
Could you check for it?

**Comment by hemanth** [comment] 2016-06-27 13:21
Merged.

**Closed by hemanth** 2016-06-27 13:21 UTC

**Comment by logological** [comment] 2016-06-30 12:53
So is using the clone URL supposed to be supported now?  It still doesn't work for me (and yes, I did enter my correct username and password):
```
$ git fork 'git@github.com:rubo77/rsync-homedir-excludes.git'
Enter your github username
logological
Enter host password for user 'logological':
{
  "message": "Not Found",
  "documentation_url": "https://developer.github.com/v3"
}
Cloning into 'rsync-homedir-excludes.git'...
remote: Invalid username or password.
fatal: Authentication failed for 'https://github.com/logological/rsync-homedir-excludes.git/'
/usr/local/bin/git-fork: line 45: cd: rsync-homedir-excludes.git: No such file or directory
fatal: Not a git repository (or any parent up to mount point /home)
Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).
fatal: Not a git repository (or any parent up to mount point /home)
Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).
```

The command does work if I pass it the bare user/repository name, though this checks out the fork via HTTPS rather than SSH:

```
$ git fork 'rubo77/rsync-homedir-excludes'                   
Enter your github username
logological
Enter host password for user 'logological':
…
 * [new branch]      master     -> upstream/master
$ git remote -v
origin  https://github.com/logological/rsync-homedir-excludes (fetch)
origin  https://github.com/logological/rsync-homedir-excludes (push)
upstream        https://github.com/rubo77/rsync-homedir-excludes (fetch)
upstream        https://github.com/rubo77/rsync-homedir-excludes (push)
```
