### ISSUE TITLE
Delete Submodule does not work

### ISSUE THREAD

**Issue by Burstaholic** [tj/git-extras#277] opened 2014-11-20 17:28 UTC
Fails with error: 'fatal: Please, stage your changes to .gitmodules or stash them to proceed'

This appears to be rather outdated. The current correct procedure:

```
git submodule deinit <name>
git rm --cached <name>
rm -rf .git/modules/<name>
```

From: http://stackoverflow.com/questions/1260748/how-do-i-remove-a-git-submodule

**Comment by raviranjananalist** [comment] 2015-11-13 12:22
For Expert 5 Packers and Movers Hyderabad go to  
http://www.expert5th.in/packers-and-movers-hyderabad/
For Expert 5 Packers and Movers Bangalore go to 
http://www.expert5th.in/packers-and-movers-bangalore/
For Expert 5 Packers and Movers Mumbai go to 
http://www.expert5th.in/packers-and-movers-mumbai/

**Comment by raviranjananalist** [comment] 2015-11-13 12:22
For Expert 5 Packers and Movers Gurgaon go to 
http://www.expert5th.in/packers-and-movers-gurgaon/
For Expert 5 Packers and Movers Delhi go to 
http://www.expert5th.in/packers-and-movers-delhi/
For Expert 5 Packers and Movers Pune go to  
http://www.expert5th.in/packers-and-movers-pune/

**Comment by raviranjananalist** [comment] 2015-11-13 12:22
For Expert 5 Packers and Movers Chennai go to 
http://www.expert5th.in/packers-and-movers-chennai/
For Expert 5 Packers and Movers Noida go to 
http://www.expert5th.in/packers-and-movers-noida/
For Expert 5 Packers and Movers Thane go to 
http://www.expert5th.in/packers-and-movers-thane/
For Expert 5 Packers and Movers Navi Mumbai go to 
http://www.expert5th.in/packers-and-movers-navimumbai/
For Expert 5 Packers and Movers Ghaziabad go to 
http://www.expert5th.in/packers-and-movers-ghaziabad/
For Expert 5 Packers and Movers Faridabad go to 
http://www.expert5th.in/packers-and-movers-faridabad/

**Comment by raviranjananalist** [comment] 2015-11-13 12:22
For Expert 5 Packers and Movers Bangalore go to 
http://www.expert5th.in/packers-and-movers-bangalore/
For Expert 5 Packers and Movers Pune go to  
http://www.expert5th.in/packers-and-movers-pune/
For Expert 5 Packers and Movers Mumbai go to 
http://www.expert5th.in/packers-and-movers-mumbai/

**Comment by moander** [comment] 2016-01-29 20:12
I got this error using @Burstaholic method:
```
error: the following file has changes staged in the index:
    my-subrepo
(use --cached to keep the file, or -f to force removal)
```

Using -f on deinit and then manually modifying .gitmodules worked for me:
```
git submodule deinit -f <name>
git rm --cached <name>
rm -rf .git/modules/<name>

nano .gitmodules

git commit .gitmodules -m foobar
```

**Comment by hemanth** [comment] 2016-05-13 09:01
@Burstaholic Facing the same?

**Comment by geeeeeeeeek** [comment] 2016-05-17 05:34
Same here.

```
$ git rm --cached -rf *
fatal: Please, stage your changes to .gitmodules or stash them to proceed
```

**Comment by hemanth** [comment] 2016-05-17 05:40
//cc @spacewander

**Comment by malhal** [comment] 2016-05-31 20:51
I hit the same problem but worked around it by manually deleting the module entry from .gitmodules

**Comment by hemanth** [comment] 2016-06-01 00:20
Folks, can anyone of you confirm that [this](https://github.com/tj/git-extras/pull/536) fixes your issues on your evn?

**Comment by geeeeeeeeek** [comment] 2016-06-01 14:32
@hemanth Sorry, I reseted my git repo and got it working. Now I cannot reproduce this issue.

**Comment by hemanth** [comment] 2016-06-01 14:37
Okies, merged that PR then, thank you.

**Closed by hemanth** 2016-06-01 14:37 UTC
