### ISSUE TITLE
git changelog not working properly

### ISSUE THREAD

**Issue by revolter** [tj/git-extras#305] opened 2015-01-27 15:12 UTC
Firstly, I don't see any difference in the output when using different values for the `--tag` parameter.
And it creates a `History.md` file that contains a couple of comments twice:

```

2.0 / 2015-01-27
================

  * Merge remote-tracking branch 'origin/Design' into Development
  * changed app version to 2.2

2.0 / 2015-01-27
================

  * Merge remote-tracking branch 'origin/Design' into Development
  * changed app version to 2.2

```

but the last tag is 2.2 and not all the actual commits are included

**Comment by hemanth** [comment] 2015-01-27 16:05
Facing this on tagged as well?

**Comment by revolt666** [comment] 2015-01-27 16:13
I'm sorry, I don't understand what you mean by _"tagged"_

**Comment by hemanth** [comment] 2015-01-28 03:30
[tag/2.2.0](https://github.com/tj/git-extras/releases/tag/2.2.0)

**Comment by revolt666** [comment] 2015-01-30 14:51
With the new version I get:

```

n.n.n / 2015-01-30
==================

  * stuff 6
...
  * stuff 2
  * stuff 1

```

where the commit `stuff 2` is tagged with `2.2.1`

**Comment by hemanth** [comment] 2015-01-30 16:21
@spacewander Got some time?

**Comment by spacewander** [comment] 2015-02-01 15:50
Sorry for the late reply. I started to read the code just now. 
So far, what I can make sure is, `git changelog` only generalize changelog **since the previous tag**. And the `--tag` parameter just specify the `TAG` variable of the template. If `--tag` parameter is not specified, this variable will be `n.n.n`. In a word, change the value of `--tag` just change the title of new changelog.
I am reading it deeply to figure out other problems.

**Comment by hemanth** [comment] 2015-02-01 16:01
:+1:

**Comment by revolt666** [comment] 2015-02-02 07:43
@spacewander, I see. I thought that the `--tag` parameter specifies the version for the changelog, so, for example, I could see the changelog of the version 2.2.1 _(the changes between 2.2.0 and 2.2.1)_ and the changelog of the current version _(the changes after 2.2.1)_. Also, what does `generalize changelog` implies?

**Comment by spacewander** [comment] 2015-02-02 08:55
@revolt666 
Err... By using `generalize changelog` I mean `git changelog` only show you changelog after lastest tag.
The word I use probably not suitable enough, because I am not a native English speaker, hope you can excuse me.

You said, 
>  the commit `stuff 2` is tagged with `2.2.1`

So, what the latest tag is? 2.2.1 or 2.2? And are there any commit log missed?

**Comment by revolt666** [comment] 2015-02-02 09:03
@spacewander, I see, and, no problem, I'm not a native english speaker too.

And, as of the time of writing this and the second result posted _(the one you quoted from)_, the last tag is `2.2.1`.

**Comment by spacewander** [comment] 2015-02-02 13:54
@revolt666 
Sorry, I still can not reproduce it after trying on several git repo...
I actually figure out a bug, but it is about #303 .

**Comment by hemanth** [comment] 2015-04-28 12:30
Fixed in the new release.

**Closed by hemanth** 2015-04-28 12:30 UTC
